### ISSUE TITLE
Can't convert Nami base skin

### ISSUE THREAD

**Issue by sweetriverfish** [Crauzer/lol2gltf#29]
I have used Obsidian to extract Nami's base skin and tried to convert it to glTF but it failed with some long. I then tried the older version, 2.0.1, and it worked.
![image(14)](https://user-images.githubusercontent.com/13397494/233838283-c16467a7-d3c7-4c7c-8867-5e98738e8234.png)

**Comment by QuePast** [comment]
Same problem

nami
Unhandled exception. System.NotFiniteNumberException: value
   at SharpGLTF.Memory.FloatingAccessor.set_Item(Int32 rowIndex, Int32 subIndex, Single value)
   at SharpGLTF.Memory.Vector3Array.set_Item(Int32 index, Vector3 value)
   at SharpGLTF.Memory.EncodedArrayUtils._CopyTo[T](IEnumerable`1 src, IList`1 dst, Int32 dstOffset)
   at SharpGLTF.Memory.Vector3Array.Fill(IEnumerable`1 values, Int32 dstStart)
   at LeagueToolkit.IO.Extensions.Utils.GltfUtils.CreateVertexMemoryAccessors(IVertexBufferView vertexBuffer)+MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at LeagueToolkit.IO.SimpleSkinFile.SimpleSkinGltfExtensions.CreateGltfMesh(ModelRoot root, SkinnedMesh skinnedMesh, Byte[] influenceLookup, IReadOnlyDictionary`2 materials)
   at LeagueToolkit.IO.SimpleSkinFile.SimpleSkinGltfExtensions.ToGltf(SkinnedMesh skinnedMesh, RigResource rig, IEnumerable`1 textures, IEnumerable`1 animations)
   at lol2gltf.CLI.Program.ConvertSkinnedMeshToGltf(SkinnedMeshToGltfOptions options) in D:\a\lol2gltf\lol2gltf\lol2gltf.CLI\Program.cs:line 66
   at lol2gltf.CLI.Program.<>c.<Main>b__0_0(SkinnedMeshToGltfOptions opts) in D:\a\lol2gltf\lol2gltf\lol2gltf.CLI\Program.cs:line 31
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 notParsedFunc)
   at lol2gltf.CLI.Program.Main(String[] args) in D:\a\lol2gltf\lol2gltf\lol2gltf.CLI\Program.cs:line 28
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\bone\proc\filter.py", line 34, in <module>
    subprocess.run(cmd_args, shell=True, check=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1264.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['lol2gltf.CLI.exe', 'skn2gltf', '-m', 'C:\\Users\\Admin\\Desktop\\bone\\proc\\assets\\characters\\nami\\skins\\base\\nami.skn', '-s', 'C:\\Users\\Admin\\Desktop\\bone\\proc\\assets\\characters\\nami\\skins\\base\\nami.skl', '-g', 'C:\\Users\\Admin\\Desktop\\bone\\proc\\output\\nami']' returned non-zero exit status 3762504530.

**Comment by QuePast** [comment]
![image](https://github.com/Crauzer/lol2gltf/assets/8728328/595ea13f-c142-4170-b79d-ea53d6ded605)

**Comment by QuePast** [comment]
Nami, Vayne, Zac same error
Edit .... works in [3.0.0-beta.1](https://github.com/Crauzer/lol2gltf/releases/tag/3.0.0-beta.1)
