### ISSUE TITLE
Any Example or Detailed Documents on CLI Args？

### ISSUE THREAD

**Issue by Cyux07** [Crauzer/lol2gltf#42]
work fine on just skl，skn and animation. But using with--textures and --materials, there are always a lot of strange errors. I think it's because there is something wrong with my parameter format?

```
PS F:\GameAssets> .\lol2gltf.CLI.exe skn2gltf -m F:\GameAssets\EZ\assets\characters\ezreal\skins\base\ezreal_base.skn -s F:\GameAssets\EZ\assets\characters\ezreal\skins\base\ezreal_base.skl -a F:\GameAssets\EZ\assets\characters\ezreal\skins\base\animations\ --textures F:\GameAssets\EZ\assets\characters\ezreal\skins\base\ -g ./ezreal.glb
Unhandled exception. System.InvalidOperationException: Material name count and Animation path count must be equal
   at lol2gltf.CLI.Program.ConvertSkinnedMeshToGltf(SkinnedMeshToGltfOptions options) in D:\a\lol2gltf\lol2gltf\lol2gltf.CLI\Program.cs:line 46
```
```
PS F:\GameAssets> .\lol2gltf.CLI.exe skn2gltf -m F:\GameAssets\EZ\assets\characters\ezreal\skins\base\ezreal_base.skn -s F:\GameAssets\EZ\assets\characters\ezreal\skins\base\ezreal_base.skl -a F:\GameAssets\EZ\assets\characters\ezreal\skins\base\animations\ --textures F:\GameAssets\EZ\assets\characters\ezreal\skins\base\ --materials M_Ezreal_base -g ./ezreal.glb
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\GameAssets\EZ\assets\characters\ezreal\skins\base\'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
```
My file structure is as follows：
F:\GameAssets\EZ\assets\characters\ezreal\skins\base\
 - animations\
 - - ezreal_attack1.anm
 - - ...
 - ezreal_base.skl
 - ezreal_base.skn
 - ezreal_base_idol_tx_cm.dds
 - ezreal_base_tx_cm.dds
 - 2x_ezreal_base_idol_tx_cm.dds
 - 2x_ezreal_base_tx_cm.dds
 - 4x_ezreal_base_idol_tx_cm.dds
 - 4x_ezreal_base_tx_cm.dds

**Comment by Crauzer** [comment]
The first error:
` Material name count and Animation path count must be equal`
Basically `--materials` defines the material names and then `--textures` defines the textures for those materials in the same order.

**Comment by ssnangua** [comment]
> The first error: ` Material name count and Animation path count must be equal` Basically `--materials` defines the material names and then `--textures` defines the textures for those materials in the same order.

How to get the material name?

**Comment by Crauzer** [comment]
Good question, there are many ways you can obtain material names, although the issue here is the fact that `lol2gltf` itself cannot tell you this. I will add a command for getting info out of meshes so you can accurately assign the materials.

**Comment by Crauzer** [comment]
For now you should be able to just convert the mesh without textures, then check material names in Blender for example, and backtrack to fill them into the command.

**Comment by xGitHubUser999x** [comment]
lol2gltfGUI Python script: https://www.youtube.com/watch?v=h9_NLzIP-pU

**Comment by bean055** [comment]
im getting no errors on the CLI cmd after fixing hierarchy but its still not outputting a .skn file?
